---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guido.
--- DateTime: 06/02/2025 18:39
---
---@class ElementUtils
local ElementUtils = {}


function ElementUtils.inheritsFrom(obj, base)
    local mt = getmetatable(obj)
    while mt do
        if mt == base then
            return true
        end
        mt = getmetatable(mt).__index -- Move up the inheritance chain
    end
    return false
end

return ElementUtils