---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guido.
--- DateTime: 06/02/2025 20:03
---


local Region = {}



function Region.new(x,y,width,height)
    local obj = setmetatable({}, self)
    obj.x = x or 0
    obj.y = y or 0
    obj.width = width or 10
    obj.height = height or 5
    return obj
end